### ISSUE TITLE
[Compatibility] 'Slight' Gui Modifications Satisfying screenshot

### ISSUE THREAD

**Issue by RyanCR03** [CreeperHost/BlockShot#1]
'Slight' Gui Modifications Satisfying screenshot animation does not play when using blockshot.

**Comment by ThePaul-T** [comment]
Can you provide links to the mod, what version and minecraft version you're using of blockshot, anything else useful.

**Comment by RyanCR03** [comment]
['Slight' GUI Modifications](https://www.curseforge.com/minecraft/mc-mods/slight-gui-modifications)
And i was using fabric 1.0.0 but i'll see with latest

**Comment by RyanCR03** [comment]
still doesnt animate in latest version

**Comment by ThePaul-T** [comment]
Can't really think of a sane way to fix this, as we cancel the event to ensure your own filesystem doesn't get cluttered with files when we're uploading. Seems saner to miss the animation in this case but keep our expected behaviour.
