### ISSUE TITLE
Immense lag with Block Shot 1.12.2 and Modpack

### ISSUE THREAD

**Issue by roccscout** [CreeperHost/BlockShot#2]
180+ mod modpack and massive lag when using blockshot unfortunately. Massive CPU spike, then crashed the game.

**Comment by ThePaul-T** [comment]
You'll need to assign more memory if you're expecting to create long animated gifs, each frame needs stored to memory before it can be encoded.

CPU spikes will be garbage collection trying to stop you running out of memory.

**Comment by ThePaul-T** [comment]
Been able to find a more memory efficient way to encode the gifs, seems the library I used originally was not cleaning up after it's self so was eating huge amounts of memory.

Try version 1.2.5
