### ISSUE TITLE
Lags

### ISSUE THREAD

**Issue by Stin045** [CreeperHost/BlockShot#3]
first of all specs RTX3060 , Ryzen 5 3600, 16gig of ram, 10 gb allocated to mc

and the Blockshot is lagging my game very very... strongly ? i suppose .

**Comment by ThePaul-T** [comment]
https://valid.x86.fr/9hy0fs

I don't lag :)

Can you try again, but with MC version, BlockShot version, maybe an idea of what mods you have, how much memory you're actually using from f3, as it'll need a bunch of space ram.

This basically works by turning your frame buffer into a byte array, then sending it off into another thread, there is very little optimisations left to do...

**Comment by ThePaul-T** [comment]
Been able to find a more memory efficient way to encode the gifs, seems the library I used originally was not cleaning up after it's self so was eating huge amounts of memory.

Try version 1.2.5
