### ISSUE TITLE
Save locally as well as uploading

### ISSUE THREAD

**Issue by MichaelHillcox** [CreeperHost/BlockShot#5]
Currently the code mixin stops the original method for the screenshot functionality meaning the code never allows the image to actually save to the clients screenshot files. Upon this, it would be good have gifs also go into the screenshots folder :D

**Comment by ThePaul-T** [comment]
I think I already moved the ci.cancel and committed... Just can't get my home dev env to work well enough to test/compile etc... Tuesday hopefully.

**Comment by MichaelHillcox** [comment]
Awesome! Thanks paul

**Comment by gigabit101** [comment]
Closing this issue due to the issue already being resolved
