### ISSUE TITLE
Causes game crash on Linux when opening the controls screen

### ISSUE THREAD

**Issue by ghost** [CreeperHost/BlockShot#6]
Playing on Manjaro Linux 5.15.38-1-MANJARO using X11 and KDE Plasma 5.24.5
Error [25May2022 23:58:46.309] [Render thread/ERROR] [net.minecraftforge.eventbus.EventBus/EVENTBUS]: Exception caught during firing event: Cannot read field "uploadMode" because "net.creeperhost.blockshot.Config.INSTANCE" is null is thrown and client immediately crashes.
Log below:
[latest.log](https://github.com/CreeperHost/BlockShot/files/8777026/latest.log)
EDIT: ran a quick `cat latest.log | grep "ERROR" > errors.txt` for you, so you don't have to comb through thousands of lines of log output:
[errors.txt](https://github.com/CreeperHost/BlockShot/files/8777043/errors.txt)

**Comment by AHSauge** [comment]
In case someone needs a temporary fix. Deleting the file `blockshot.json` in the instance folder (aka. where you can find `instance.json` and `options.txt`) or alternatively, ensure that it looks something like this

```JSON
{
  "uploadMode": 1,
  "anonymous": true
}
```
fixes the problem. For some reason it seems that I've ended up with a blank file, causing the issues mentioned above.

**Comment by gigabit101** [comment]
This should be fixed in later builds of the mod
